### ISSUE TITLE
Go race with Mock

### ISSUE THREAD

**Issue by stevedalton** [benbjohnson/clock#44]
I believe the following demonstrates the issue:

```
c := clock.NewMock()
go c.Ticker(time.Second).Stop()
c.Add(time.Second)
```
Unfortunately, it's hard to get Go's race detector to catch this (I only ran it across it in a more complicated case by accident).

The detailed problem is as follows:
- The internal method `removeClockTimer` sorts the timers while holding the mutex. The sort method calls `Next()`, which reads the internal `next` field.
- The internal method `runNextTimer` calls `Tick` on the timer _without holding the mutex_, and `Tick` sets the internal `next` field of the timer.

It seems that solving this might just require removing the `sort.Sort` call in `removeClockTimer`.

**Comment by djmitche** [comment]
Removing the `sort` would still leave `runNextTimer` modifying things without protection, so that's not a good fix.
