### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by vincentbernat** [benbjohnson/clock#47]
Hey!

There are some pull requests fixing long standing bugs. Would it be possible to merge them and release a new version. Notably:
- #42
- #45 (need an additional patch for tests, https://github.com/benbjohnson/clock/commit/739bd11b5833f87d3d77433c9c4876aa2f6e580a)
- #46

Also, could be interesting:
- #43 (I would also add "1.x" to the list of tested versions)

I am using these patches: https://github.com/benbjohnson/clock/compare/master...vincentbernat:vbe/master. Tests pass: https://github.com/vincentbernat/go-clock/actions/runs/3111243171.

**Comment by djmitche** [comment]
I apologize -- I am the nominal maintainer of this repo, but apparently wasn't watching it. I will take a look.

**Comment by djmitche** [comment]
Done, and released as 1.3.3
