### ISSUE TITLE
Issue adding time to mocked clock

### ISSUE THREAD

**Issue by nathanjohnson320** [benbjohnson/clock#7]
In the below code I get an error:
```
mockClock := clock.NewMock()
mockClock.Add(2 * time.Hour)
```
mockClock.Add undefined (type clock.Clock has no field or method Add)

Is there another function I should be using instead?

**Comment by benbjohnson** [comment]
@nathanjohnson320 `NewMock()` returns a `*Mock` which has an `Add()` method. Do you have the latest code from the repo?

https://godoc.org/github.com/benbjohnson/clock#NewMock
